name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: islandoftex
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run latexmk
        run: |
          cd latex
          latexmk template.tex

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: |
            latex/template.pdf
